# Generated by Django 4.0.1 on 2022-06-20 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryboy_added_by_deliveryboy_is_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
