# Generated by Django 4.0.1 on 2022-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryboy_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_boy'),
        ),
    ]
