# Generated by Django 4.0.1 on 2022-05-24 11:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ph_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
