# Generated by Django 4.0.1 on 2022-08-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
