# Generated by Django 4.0.1 on 2022-05-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_product_slug'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminn.option'),
            preserve_default=False,
        ),
    ]
