# Generated by Django 4.0.1 on 2022-05-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0004_option_in_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_cart_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidOrder',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='orders/')),
                ('unit_size', models.CharField(max_length=200)),
                ('product_color', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_discount', models.FloatField(default=0)),
                ('product_brand', models.CharField(max_length=255)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('midorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.midorder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('total_discount', models.FloatField(default=0)),
                ('rz_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rz_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('coupon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='midorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.order'),
        ),
        migrations.AddField(
            model_name='midorder',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminn.option'),
        ),
    ]
