# Generated by Django 4.0.1 on 2022-05-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('client', '0005_midorder_delivered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryboy'),
        ),
    ]
