# Generated by Django 4.0.1 on 2022-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_midorder_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='midorder',
            name='status',
            field=models.CharField(default='order_placed', max_length=255),
        ),
    ]
