# Generated by Django 4.0.1 on 2022-05-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_midorder_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midorder',
            old_name='pid',
            new_name='product',
        ),
    ]
