# Generated by Django 4.0.1 on 2022-05-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0004_option_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
