# Generated by Django 4.0.1 on 2022-07-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0007_brand_created_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminn.product'),
            preserve_default=False,
        ),
    ]
