# Generated by Django 4.0.1 on 2022-07-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0009_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
