# Generated by Django 4.0.1 on 2022-07-13 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminn', '0009_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer_name',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
