# Generated by Django 4.0.1 on 2022-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0010_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_pincodes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
