# Generated by Django 4.0.1 on 2022-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0011_product_expected_pincodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('top', 'Top Region'), ('bottom', 'Bottom Region')], max_length=255)),
                ('categories', models.ManyToManyField(to='adminn.Category')),
            ],
        ),
    ]
